name: "PyWinRM"
description: "Connect to WinRM using PyWinRM"
inputs:
  server_name:
    description: Server Name to Connect
    required: true
runs:
  using: composite
  steps:
    - name: Run WinRM Connect
      run: python winrm-connection.py ${{ inputs.server_name }}
      shell: bash
