name: "PyWinRM"
description: "Connect to WinRM using PyWinRM"
inputs:
  pwsh:
    description: Powershell Command
    required: true
runs:
  using: composite
  steps:
    - name: Run WinRM Connect
      run: python ./.github/actions/winrm-connect/winrm-connection.py ${{ inputs.pwsh }}
      shell: bash
