name: GitHub Actions Demo
run-name: Deployment on ${{ inputs.environment }} by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment Name"
        required: true
        type: environment
jobs:
  Demo-Action:
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Deploying on ${{ inputs.environment }}"
      - run: ping ${{ vars.SQL_SERVER }} -4 -c 4
      - name: Run simple powershell command
        uses: trxharu/workflow-playground/.github/workflows/winrm-connect.yml@main
        with:
          server_name: ${{ vars.SQL_SERVER }}
