name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment Name"
        required: true
        type: environment
jobs:
  Demo-Action:
    runs-on: self-hosted
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repo code
        uses: actions/checkout@v5
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - run: echo "deploying on ${{ inputs.environment }}"
      - run: echo "${{ vars.SQL_SERVER }}"
